# Generated by Django 3.0 on 2021-11-19 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atracao',
            old_name='idade_minimo',
            new_name='idade_minima',
        ),
    ]
